# Generated by Django 5.0.3 on 2024-04-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employe_password_employe_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
